apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '16'
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["10.110.214.196"],"port":80,"protocol":"HTTP","serviceName":"ecommerce-backend:ecommerce-backend-service","ingressName":"ecommerce-backend:ecommerce-backend-ingress","hostname":"api-ecommerce.devopsedu.vn","path":"/","allNodes":false}]
    objectset.rio.cattle.io/applied: >-
      H4sIAAAAAAAA/5SRQW/bMAyF/wuB3ezGVmLY1W3YDjv0EGzrLkMPlMQkWmVJkNisRqD/PihBiw5rUexI4vF9JN8JMNoflLINHiRgjHl17KGBe+sNSPhM0YVlJs/QwEyMBhlBngC9D4xsg8+1DOoXac7EV8mGK43Mjq5sWNlqYkYcdkqMrRhM3270NLVI1LejUnqYNjtaKwWlAYeK3NkOYwQJpMM8U9LUKtT35A00b4IOmA8gYezUIMRus5t6Wo+iu9ajMJ0Yr/sRezMZFOtNp7WpOI8zvUZpzcujqypH1K9Kq02OpOvOiaKzGjNI0UCio60//WIzh7Tc2NkyyL5vIJMjzSHVkRlZH27evbpUCidk2i9nUnDO+v1tNMh08Xn89pD2dUUxfKhJ4eOtxyNah8o9tUsDvMRaff3LoPZpju7J7EXK7ydS/uNDOnhG6yllkD9PYGc8r4yx2/Ri9c+oPApoLqrtg3Pb4KxeQMJH9xuXDG8HCA3EkPhCeYZuQ2KQUzd1z5OsY9WmwEEHBxK+f9pCuSt3pZTyJwAA///g1LlUGwMAAA
    objectset.rio.cattle.io/id: d7a5fb27-25d1-4c88-aee1-7bbc584fe3bb
  creationTimestamp: '2025-03-29T06:49:38Z'
  generation: 24
  labels:
    app: ecommerce-backend
    objectset.rio.cattle.io/hash: 70b522f4f81e37209c72d027917a1d8da2340ccd
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/publicEndpoints: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
          f:labels:
            .: {}
            f:app: {}
            f:objectset.rio.cattle.io/hash: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:cattle.io/timestamp: {}
              f:labels:
                .: {}
                f:app: {}
              f:namespace: {}
            f:spec:
              f:containers:
                k:{"name":"ecommerce-backend"}:
                  .: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":8080,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:name: {}
                      f:protocol: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/run/src/main/resources/application.properties"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                      f:subPath: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
              f:volumes:
                .: {}
                k:{"name":"ecommerce-backend-application-properties-config-volume"}:
                  .: {}
                  f:configMap:
                    .: {}
                    f:defaultMode: {}
                    f:name: {}
                  f:name: {}
      manager: agent
      operation: Update
      time: '2025-03-30T04:20:06Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2025-03-30T04:20:20Z'
  name: ecommerce-backend-deployment
  namespace: ecommerce-backend
  resourceVersion: '51613'
  uid: 26edd96e-4fed-41fc-9db7-0f79852130e5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 11
  selector:
    matchLabels:
      app: ecommerce-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2025-03-30T03:57:28Z'
      creationTimestamp: null
      labels:
        app: ecommerce-backend
      namespace: ecommerce-backend
    spec:
      containers:
        - image: devopseduvn/ecommerce-backend:v1
          imagePullPolicy: Always
          name: ecommerce-backend
          ports:
            - containerPort: 8080
              name: tcp
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File





# Lưu ý
          volumeMounts:
            - mountPath: /run/src/main/resources/application.properties
              name: ecommerce-backend-application-properties-config-volume
              subPath: application.properties


      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30






#  Lưu ý

      volumes:
        - configMap:
            defaultMode: 420
            name: ecommerce-backend-application-properties-configmap
          name: ecommerce-backend-application-properties-config-volume
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2025-03-30T04:20:20Z'
      lastUpdateTime: '2025-03-30T04:20:20Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2025-03-29T06:49:38Z'
      lastUpdateTime: '2025-03-30T04:20:20Z'
      message: >-
        ReplicaSet "ecommerce-backend-deployment-596fbbdc7c" has successfully
        progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 24
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
